Jango/Home/urls.py
from django.urls import path
from Home import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    path('art_list/', views.art_list, name='art_list'),
    path('detail/<int:article_id>', views.detail, name='detail'),
    path('create_article/', views.create_article, name='create_article'),
    path('edit_article/<int:article_id>', views.edit_article, name='edit_article'),
    path('delete_article/<int:article_id>', views.delete_article, name='delete_article'),
    path('article_category/<int:category_id>', views.get_article_by_category, name='article_category'),
    path('article_author/<int:author_id>', views.get_article_by_author, name='article_author'),
]

Jango/Jango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('home_page.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Jango/account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('log_in/', views.log_in, name='user_log_in'),
    path('log_out/', views.log_out, name='user_log_out'),
    path('register/', views.register, name='user_register'),
]

Jango/Home/models.py
from django.db import models
from django.contrib.auth.models import User
from category.models import Category

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100,verbose_name = "عنوان مقاله") # , null=True, blank=True
    text = models.TextField(help_text="Enter your article text.", verbose_name="متن")
    pub_date = models.DateTimeField(auto_now_add=True,verbose_name ="تاریخ انتشار")
    updated_date = models.DateTimeField(auto_now=True ,verbose_name ="تاریخ بروز رسانی")
    is_show = models.BooleanField(default=True,verbose_name = "ایا مقاله نمایش داده شود")
    image = models.ImageField(upload_to="Home/image_article/",verbose_name ="تصویر")
    auther = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name ="نویسنده") # این باعث میشه که فقط فردی از بین کاربران ثبت نام شده در این سایت رو بشه به عنوان نویسنده انتخاب کرد
    categoreis = models.ManyToManyField(Category)
# "Person", on_delete=models.CASCADE یععنی برو به مدل person و اگر هم person حذف شد مقالاتش هم حذف بشه
    def __str__(self): # هر وقت کلاس فراخوانی بشه تایتلش برگردونده میشه که توی ادمین پنل این اتفاق میوفته و تایتل هر مقاله نمایش داده میشه
        return self.title

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

class Person(models.Model):
    first_name = models.CharField(max_length=200,verbose_name ="نام")
    last_name = models.CharField(max_length=200,verbose_name ="نام خانوادگی")
    email = models.EmailField(verbose_name ="ایمیل")
    age = models.IntegerField(default=0,verbose_name = "سن")
    website_url = models.URLField(max_length=200)
    score = models.FloatField()
    score_2 = models.DecimalField(max_digits=5, decimal_places=2, default=0)
# max_digits=5 یعنی عدد حداکثر 5 رقم میتونه داشته باشه
# decimal_places=2 یعنی دو تا رقم اعشاری میتونه داشته باشه

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.id} "

    class Meta:
        ordering = ['age']
        verbose_name = "شخص"
        verbose_name_plural = "اشخاص"

Jango/Home/forms.py
from django import forms
from django.core.exceptions import ValidationError

error_message = {
    'required':'مقدار دهی به این فیلد ضروری هست',
    'invalid':'مقداری که به این فیلد داده اید نا معتبر است'
}


class CreateArticleForm(forms.Form):
    Title = forms.CharField(max_length=100, label="عنوان داستان ", widget=forms.TextInput(attrs={'class':'form-control'}), help_text="Enter title the story.")
    Text = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}), label="متن داستان ", error_messages=error_message)
    Image = forms.ImageField(label="تصویر داستان ", widget=forms.FileInput(attrs={'class':'form-control'}))
    is_show = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'form-check-input'}), required=False, label="ایا داستان نمایش داده شود یا در حالت پش نوس قرا بگیرد ؟ ")
    # auther = forms.IntegerField(widget=forms.NumberInput(attrs={'class':'form-control'}), label="نام نویسنده ")
# نام نویسنده دیگه لازم نیست که وارد بشه چون به صورت خودکار نام کاربری که مقاله رو ایجاد کرده قرار میگیره

    # def clean_Title(self):
    #     title = self.cleaned_data['Title']
    #     if 'iran' not in title.lower():
    #         print("user")
    #         raise ValidationError('this title has to has word iran.')
    #     return title

class EditArticleForm(forms.Form):
    Title = forms.CharField(max_length=100, label="عنوان داستان ",widget=forms.TextInput(attrs={'class': 'form-control'}), help_text="Enter title the story.")
    Text = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control'}), label="متن داستان ",error_messages=error_message)
    Image = forms.ImageField(label="تصویر داستان ", widget=forms.FileInput(attrs={'class': 'form-control'}), required=False)
    is_show = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}), required=False,label="ایا داستان نمایش داده شود یا در حالت پش نوس قرا بگیرد ؟ ")

Jango/Home/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden, Http404
from . import forms
from .forms import CreateArticleForm, EditArticleForm
from .models import Article, Person  # جدول رو از دیتابیس فراخونی
# میکنم تا به اطلاعاتش دسترسی داشته باشم
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from category.models import Category

# Create your views here.

def home(request):
    logout(request)
    articles = Article.objects.all().filter(is_show=True)
    context = {
        'art':articles
    }
    return render(request, 'Home/home.html', context)

def art_list(request):
    articles = Article.objects.all().filter(is_show=True)
    authors = User.objects.all()
    categories = Category.objects.all()
    search_line = request.GET.get('search')
    if search_line:
        articles = articles.filter(title__icontains=search_line)

    paginator = Paginator(articles, 3)
    page_number = request.GET.get('page') # شماره صفحه ای رو که کاربر درخواست کرده رو دریافت میکنه
    page_obj = paginator.get_page(page_number) # اطلاعات صفحه ی در خواست شده رو دریافت میکنه

    context = {
        'page_obj':page_obj,
        'categories':categories,
        'authors':authors,
    }
    return render(request, 'Home/art_list.html', context)

def detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    categories = article.categoreis.all()
    print(categories)
    return render(request, 'Home/detail.html', {'article':article, 'categories':categories})

@login_required(login_url='/account/log_in/')
def create_article(request):
    # if request.user.is_authenticated:  ایف و الس بررسی میکنن که ایا کاربر لاگین کرده یا نه و بجای این کار میشه از دیکوریتور استفاده کرد هر چند که اصلا بدون لاگین کردن امکان ورود وجود نداره
    print(f"Request method is : {request.method}")
    if request.method == "POST":
        form = CreateArticleForm(data=request.POST, files=request.FILES)
        print(f'request Files : {request.FILES}')
        print(f"Form is valid : {form.is_valid()}")
        if form.is_valid():
            print(form.cleaned_data)
            title = form.cleaned_data.get('Title')
            text = form.cleaned_data.get('Text')
            image = form.cleaned_data.get('Image')
            is_show = form.cleaned_data.get('is_show')
            Article.objects.create(title=title, text=text, image=image, is_show=is_show,
                                   auther=request.user)
            print("Article created")
            return redirect('home:art_list')
    else:
        form = CreateArticleForm()
    return render(request, 'Home/create_article.html', {"form":form})

@login_required(login_url='/account/log_in/')
def edit_article(request, article_id):
    art = get_object_or_404(Article, id=article_id, auther_id=request.user.id)
    print(f"Editing article: {art}")
    if request.method == "POST":
        print(f"Request method is POST")
        form = EditArticleForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            print(f"Form is valid: {form.cleaned_data}")
            art.title = form.cleaned_data.get('Title')
            art.text = form.cleaned_data.get('Text')
            image = form.cleaned_data.get('Image')
            # فقط اگر تصویر جدید بارگذاری شود، آن را به روز می‌کنیم
            if image:
                art.image = image
            art.is_show = form.cleaned_data.get('is_show')
            art.save()
            print("Article edited")
            return redirect('home:detail', article_id=article_id)
    else:
        print(f"Request method is GET")
        form = EditArticleForm(initial={
            'Title': art.title,
            'Text': art.text,
            'Image': art.image,
            'is_show': art.is_show
        })

    return render(request, 'Home/article_edit.html', {"form": form, "article": art})

def delete_article(request, article_id):
    art = get_object_or_404(Article, id=article_id, auther_id=request.user.id)
    art.delete()
    return redirect('home:art_list')

def get_article_by_category(request, category_id):
    articles = Article.objects.filter(categoreis=category_id)
    paginator = Paginator(articles, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj}
    return render(request, 'Home/art_list.html', context)


def get_article_by_author(request, author_id):
    author = get_object_or_404(User, id=author_id)
    articles = Article.objects.filter(auther_id=author_id)
    paginator = Paginator(articles, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj':page_obj,
               'author':author}
    return render(request, 'Home/art_list.html', context)

Jango/Home/templates/Home/art_list.html
{% extends 'base/base.html' %}

{% block title %}داستان ها{% endblock %}

{% block body %}
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
<!--    <div class="row py-lg-5" style="background-color: rgba(255, 255, 255, 0.8); padding: 20px; border-radius: 10px;">-->
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-normal">{% if author %} Articles of {{ author.get_full_name }} {% else %} Articles {% endif %}</h1>

            <img class="background-image" src = "#" alt = ""/>
        <br>
        <p class="lead text-body-secondary">سایتی پر از داستان های کوتاه، جالب و سرگرم کننده برای فرزندان ایران زمین</p>
        <p>
          <a href="{% url 'home:create_article' %}" class="btn btn-primary my-2">اضافه کردن داستان</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
    <form action="" method="get">
      <div class="form-group">
        <input type="text" class="form-control" name="search" placeholder="Search in Articles">
          <button type="submit" class="btn btn-primary my-3">Search</button>
      </div>
    </form>
  </section>

<ul class="list-group">

  {% for category in categories %}
    <a href="{% url 'home:article_category' category.id %}"><li class="list-group-item d-flex justify-content-between align-items-center">
      {{ category }}
        <span class="badge bg-primary rounded-pill">14</span>
    </li></a>
  {% endfor %}

</ul>

  <br><br><br>
  <h3>   Author</h3>

<ul class="list-group">

  {% for author in authors %}
    <a href="{% url 'home:article_author' author.id %}"><li class="list-group-item d-flex justify-content-between align-items-center">
      {{ author.get_full_name }}
        <span class="badge bg-primary rounded-pill">14</span>
    </li></a>
  {% endfor %}

</ul>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      {% for art in page_obj.object_list %}
        <div class="col">
          <div class="card shadow-sm">
            <a href="{% url 'home:detail' art.id %}"><img class="bd-placeholder-img card-img-top" src="{{ art.image.url }}" alt={{ art.title }} height=240px width=300px>
            <br><h3 class="align-right" dir="rtl" style="padding-right: 20px">{{art.title}}</h3>
            <div class="card-body"></a>

              <p class="card-text" dir="rtl" >{{art.text|truncatechars:140}}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-body-secondary">{{art.pub_date|date:"Y M d"}}</small>
              </div>
              <small class="text-body-secondary">{{art.auther}}</small>
            </div>
          </div>
        </div>
<!--    </div>-->



      {% empty %}
          <p class="text-danger">Article not found</p>
      {% endfor %}
      </div>
    <nav aria-label="...">
  <ul class="pagination">
      <li class="page-item">
      {% if page_obj.has_previous %}
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
      </li>
    {% for page in page_obj.paginator.page_range %}
    <a class="page-link {% if page == page_obj.number %}active {% endif %}" href="?page={{ page }}">{{ page }}</a>
    {% endfor %}
      <li class="page-item">
      {% if page_obj.has_next %}
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
      {% endif %}
      </li>
  </ul>
</nav>

{% endblock %}

Jango/Home/templates/Home/article_edit.html
{% extends 'base/base.html' %}

{% block title %} Edit Article {% endblock %}

{% block body %}
<p class="text-warning">You Can Create Article With this form</p>
<form novalidate enctype="multipart/form-data" class="form-control" method="post" action="{% url 'home:edit_article' article.id %}">
  {% csrf_token %}
<!--    <div class="row mb-4"></div>-->
    <div class="col">
      <div data-mdb-input-init class="form-outline">
        {{ form.Title }}
        <label class="form-label" for="form6Example1">Title</label>
        <p class="text-info">{{ form.Title.help_text }}</p><!--ای که توی فرم مشخص کردم رو نمایش میده help_text -->
       </div>
      {% for error in form.Title.errors %}<!-- ارور های فیلد تایتل رو نشون میده -->
        <p class="text-danger">{{ error }}</p>
      {% endfor %}
    </div>
  <br>

    <div class="col">
      <div data-mdb-input-init class="form-outline">
        {{ form.Text }}
        <label class="form-label" >{{ form.Text.label }}</label><!-- نامی که برای لیبیل توی فرم گذاشتم رو نمایش میده -->
      </div>
      {% for error in form.Text.errors %}
        <p class="text-danger">{{ error }}</p>
      {% endfor %}
    </div>
  <br>
    <div data-mdb-input-init class="form-outline mb-4">
      {{ form.Image }}
      <a href="{{ article.image.url }}">Article image</a>
<!--      <label class="form-label" for="form6Example3">Image</label>-->
      {% for error in form.Image.errors %}
        <p class="text-danger">{{ error }}</p>
      {% endfor %}
    </div>
  <br>

  <div data-mdb-input-init class="form-outline mb-4">
    {{ form.is_show }}
    <label class="form-label" for="form6Example4">Do you want show this story?</label>
  </div>
<!--  <div data-mdb-input-init class="form-outline mb-4">-->
<!--    {{ form.auther }}-->
<!--    <label class="form-label" for="form6Example5">Enter id auther</label>-->
<!--  {% for error in form.auther.errors %}-->
<!--    <p class="text-danger">{{ error }}</p>-->
<!--  {% endfor %}-->
<!--  </div>-->
<!--  {{ form.errors }}&lt;!&ndash; همه ارور هایی که توی فرم هست رو میده &ndash;&gt;-->
    <button type="submit" class="btn btn-primary btn-block mb-4">Update Article</button>
</form>
{% endblock %}

Jango/Home/templates/Home/detail.html
{% extends 'base/base.html' %}

{% block title %}
{{ article.title }}
{% endblock %}

{% block body %}
<section class="py-5 text-center container" style="background-image: url('{{ article.image.url }}'); background-size: cover; background-position: center; padding: 20px; border-radius: 10px; height: 500px;">
<!--  <div class="row py-lg-5">-->
    <br><br><br>
    <div class="row py-lg-5" style="background-color: rgba(255, 255, 255, 0.4); padding: 20px; border-radius: 10px;">
     <div class="col-lg-6 col-md-8 mx-auto">
       <h1 class="fw-normal">{{ article.title }}</h1><br>
       <p class="lead text-body-secondary">Auther : {{ article.auther.get_full_name }}</p>
       {% if request.user.id == article.auther.id %}
         <a href="{% url 'home:edit_article' article.id %}" class="btn btn-primary my-2">Edit</a>
         <a href="{% url 'home:delete_article' article.id %}" class="btn btn-danger my-2">Delete</a>
       {% endif %}
     </div>
    </div>
</section>

        </div>
        <article>{{ article.text }}</article>
        <br>
        <h4>{{ article.updated_date }}</h4>
        <div>
{% for cat in categories %}
    <h6>{{ cat }}</h6>
{% endfor %}

{% endblock %}

Jango/Home/templates/Home/home.html
{% load static %}
<!doctype html>
<html lang="en" class="h-100" data-bs-theme="auto">
  <head><script src="{% static 'color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Cover Template · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<!--</head>-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="d-flex h-100 text-center text-bg-dark">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
              id="bd-theme"
              type="button"
              aria-expanded="false"
              data-bs-toggle="dropdown"
              aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em"><use href="#circle-half"></use></svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#sun-fill"></use></svg>
            Light
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#moon-stars-fill"></use></svg>
            Dark
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
        <li>
          <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
            <svg class="bi me-2 opacity-50" width="1em" height="1em"><use href="#circle-half"></use></svg>
            Auto
            <svg class="bi ms-auto d-none" width="1em" height="1em"><use href="#check2"></use></svg>
          </button>
        </li>
      </ul>
    </div>


<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3> داستان </h3>
      </nav>
    </div>
  </header>

  <main class="px-3">
    <h1>ســــــلام بــــه کــــودکان ایـــران زمـــین </h1>
    <br>
    <p class="lead" > سایتی پر از داستان های کوتاه جذاب و اموزنده برای کودکان ایران زمین </p>
    <p class="lead"><br>
      <a href="{% url 'account:user_log_in' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">Log in</a>
      <a href="{% url 'account:user_register' %}" class="btn btn-lg btn-light fw-bold border-white bg-white">register</a>
<!--      <a href="{% url 'home:create_article' %}" class="btn btn-primary my-2">create article</a>-->

    </p>
  </main>

  <footer class="mt-auto text-white-50">
    <p>Cover template for <a href="https://getbootstrap.com/" class="text-white">Bootstrap</a>, by <a href="https://twitter.com/mdo" class="text-white">@mdo</a></p>
  </footer>
</div>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

    </body>
</html>